---
- name: Backup Cisco Router or Switch
  hosts: switchaccel
  connection: network_cli
  gather_facts: false
  tasks:
    
    - name: Get current time
      local_action: command date +%H:%M
      register: time
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         #ansible_host = getting device IP, ansible_net_hostname = getting device hostname
         filename: "{{ ansible_net_hostname }}_{{ ansible_host }}.cfg"
         #Please change /home/hawar/Desktop to your direcotry
         #Every time create a new directory under named date and time
         dir_path: /root/ansible-tower/backup/at_{{ time.stdout }}
    - name: Tasks done
      debug: msg="All tasks has been done  at {{ time.stdout }}."