---
- name: first play
  hosts: poc-mysql
  tasks:
    - name: Create a new database with name 
      mysql_db:
        name: bobdata
        state: present
        login_user: root
        login_password: null